[package]
name = "macroix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
confy = "0.5.1"
kira = "0.8.5"
macroquad = { version = "0.4.4" }
midir = "0.9.1"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"

# From README:
# > Adding the following snippet to your Cargo.toml ensures that all dependencies compile in release even in debug mode.
# > In macroquad, this has the effect of making images load several times faster and your applications much more performant, while keeping compile times miraculously low.
[profile.dev.package.'*']
opt-level = 3
