[package]
name = "egui_macroquad"
version = "0.1.0"
edition = "2021"

[dependencies]
egui_miniquad = { path = "../egui_miniquad" }
egui = {version ="0.28.1", features = ["bytemuck"] }
miniquad = { version = "=0.4.5" }
macroquad = { version = "0.4.4", default-features = false }
